---
- name: Kubeadm init
  command: kubeadm init --pod-network-cidr={{kube_pod_network_cidr}} --token={{kube_token}} creates=/etc/kubernetes/admin.conf

- name: Kubeadm apply flannel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml creates=/etc/cni/net.d/10-flannel.conf
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- copy:
    dest: /etc/profile.d/kube.sh
    content: "export KUBECONFIG=/etc/kubernetes/admin.conf"
