---
- name: Install Epel
  package: name=epel-release state=installed

- name: Install docker
  package: name=docker state=installed

- name: Fix docker to use devicemapper
  lineinfile:
    path: /etc/sysconfig/docker-storage
    regexp: '^DOCKER_STORAGE_OPTIONS='
    line: 'DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper"'

- name: Fix docker to use devicemapper
  lineinfile:
    path: /etc/sysconfig/docker-storage-setup
    regexp: '^STORAGE_DRIVER='
    line: 'STORAGE_DRIVER=devicemapper'

- name: Start docker service
  service: name=docker state=started enabled=yes
  
- copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: import gpg key
  rpm_key:
    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    state: present
  register: import_key
                                                                                                       
- name: Make cache
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
  when: import_key.changed

- name: Install kubernetes packages
  package: name=kubelet-{{kube_version}},kubeadm-{{kube_version}},kubectl-{{kube_version}} state=present
  when: kube_version != "latest"

- name: Install kubernetes packages
  package: name=kubelet,kubeadm,kubectl state=latest
  when: kube_version == "latest"

- name: Start kubelet service
  service: name=kubelet state=started enabled=yes

- lineinfile:
    path: /etc/sysctl.d/k8s.conf
    regexp: '^net.bridge.bridge-nf-call-ip6tables'
    line: 'net.bridge.bridge-nf-call-ip6tables = 1'
    create: yes
  notify: sysctl-system

- lineinfile:
    path: /etc/sysctl.d/k8s.conf
    regexp: '^net.bridge.bridge-nf-call-iptables'
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    create: yes
  notify: sysctl-system

- name: sysctl-system
  command: sysctl --system

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: yes

- name: Include "{{kube_type_of_node}}" tasks
  include: "{{kube_type_of_node}}.yaml"

