---
- name: Wait for Kube master
  wait_for:
    path: /etc/profile.d/kube.sh
  delegate_to: "{{kube_server}}"

- name: Check node {{ ansible_fqdn }}
  command: kubectl get node {{ ansible_fqdn }}
  delegate_to: "{{kube_server}}"
  register: node_joined
  ignore_errors: yes

- name: Reset node
  command: kubeadm reset -f
  when: node_joined is failed
  ignore_errors: yes

- name: Add node to kube cluster
  command: kubeadm join --token {{kube_token}} {{kube_server}}:6443 --discovery-token-unsafe-skip-ca-verification creates=/etc/kubernetes/kubelet.conf
  when: node_joined is failed

- name: Add KUBELET_EXTRA_ARGS
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_EXTRA_ARGS={{kubelet_extra_args}}"'
    regexp: '^Environment="KUBELET_EXTRA_ARGS'
    insertafter: '\[Service\]'
  notify: restart kubelet
  when: kubelet_extra_args != ''